/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;
import Utils.Sistema;
import Utils.VerificadorArchivo;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 * 
 * @author wmgc5
 */
public class UIImportar extends javax.swing.JFrame {
    private Sistema sistema;
    private VerificadorArchivo verificadorArchivo;
    public UIImportar() {

        this.sistema= new Sistema();
        this.verificadorArchivo= new VerificadorArchivo();
        initComponents();

        

    }
    
    // BOTONES

    private void importarUsuariosjButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_importarUsuariosjButton1ActionPerformed
        // Variable para distintas alertas sistema
        
        // bandera
        boolean bandera = false;

        // Codigo para seleccionar un archivo y guardarlo
        File archivo=null;
        JFileChooser seleccionarArchivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos txt", "txt");
        seleccionarArchivo.setFileFilter(filtro);
        int result = seleccionarArchivo.showDialog(new JFrame(), "Abrir txt");

        if (result == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionarArchivo.getSelectedFile();

            if (archivo.getName().endsWith("usuarios.txt")) {
                bandera = true;

                sistema.verificarArchivoUsuario(bandera, "Archivo seleccionado con exito");
                

                verificadorArchivo.validarEstructuraArchivo(archivo);
                bandera = true;

            } else {
                sistema.verificarArchivoUsuario(bandera, "El nombre del archivo es incorrecto, el programa finalizará");
            }

        } else {

            sistema.verificarArchivoUsuario(bandera, "No seleccionaste ningún archivo, el programa finalizará");

        }
        //Una vez finalizado todo
       
        setVisible(false);
        UIlogin uIlogin = new UIlogin(archivo);
        uIlogin.setVisible(true);
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        importarUsuariosjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        importarUsuariosjButton1.setText("Importar Archivo Usuarios");
        importarUsuariosjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importarUsuariosjButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(importarUsuariosjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(importarUsuariosjButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton importarUsuariosjButton1;
    // End of variables declaration//GEN-END:variables

}
