/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Utils.AdministradorUsuarios;
import java.io.File;


/**
 *
 * @author wmgc5
 */
public class UIlogin extends javax.swing.JFrame {

    //

    private AdministradorUsuarios administradorUsuarios;

    public UIlogin(File archivo) {
        administradorUsuarios = new AdministradorUsuarios(archivo);
        administradorUsuarios.crearUsuarios();
        initComponents();

    }

    // BOTON JFRAME

    private void ingresarjButton1ActionPerformed(java.awt.event.ActionEvent evt,
            javax.swing.JPasswordField passwordjPasswordField1,
            javax.swing.JTextField userjTextField1) {

        String login, contrasenia;
        login = userjTextField1.getText();
        contrasenia = new String(passwordjPasswordField1.getPassword());

        boolean bandera = administradorUsuarios.verificarUsuario(login, contrasenia);

        if (bandera) {
            UImenu uImenu = new UImenu();
            setVisible(false);
            uImenu.setVisible(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordjPasswordField1 = new javax.swing.JPasswordField();
        userjTextField1 = new javax.swing.JTextField();
        ingresarjButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User");

        jLabel2.setText("Password");

        passwordjPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordjPasswordField1ActionPerformed(evt);
            }
        });

        userjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userjTextField1ActionPerformed(evt);
            }
        });

        ingresarjButton1.setText("Ingresar");
        ingresarjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarjButton1ActionPerformed(evt, passwordjPasswordField1, userjTextField1);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel1))
                                                .addGap(66, 66, 66)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(passwordjPasswordField1)
                                                        .addComponent(userjTextField1,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, 99,
                                                                Short.MAX_VALUE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(150, 150, 150)
                                                .addComponent(ingresarjButton1)))
                                .addContainerGap(162, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(userjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(passwordjPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(ingresarjButton1)
                                .addContainerGap(122, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordjPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordjPasswordField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordjPasswordField1ActionPerformed

    private void userjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userjTextField1ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_userjTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingresarjButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passwordjPasswordField1;
    private javax.swing.JTextField userjTextField1;
    // End of variables declaration//GEN-END:variables
}
